language: python
python:
- '2.7'
- '3.4'
- '3.5'
deploy:
  - provider: pypi
    server: https://testpypi.python.org/pypi
    distributions: sdist bdist_wheel
    user: lioman
    password:
      secure: cKmaYomiF0Yxn0WRtNQXdMvRbcdG9ieir3t56VK7fJQbVxW4/4Ny8hsSWp0hvr0bA86n4CJ83ahcLgyJbzSdH4AlYA9wVvxTb3diZ+h7IfE1l3CjnRiOkmYwaqfv+e19XzwSEqGevnrYTzQ4UN/SqGM2t+H0SrBnH4SDQ6oFunZ/nUYtbH3BGoYZAY580WNpUMwM13/vjCeCcXHzD68ZCSaO/JhT+hi3XKncBQZ/dYrGqlrMjx/g0sEf4JFrRXFvZZu3uEEOqJ7MmpcX78TM1SnZjZ/FALJmJwa0wEAmbbo7THGQ4L7pDLmAz/GnVeVt90zfGk2CZ7GhVaMRjhby4+wN2Jrr05mfxYpZtCO/RyXBoBDK101g3nkXhDKzFzTpg122fQL/cXzH8zIJLEaRGA6mQsOMzc2c7JIdNSPZ5fs9uD7kUYLYwUJrS1u2UY+oslDr1lsOYQALwRaKB8BdNqB+WzmWf8Pbyy2K+PPl0F8A43UqoOiFzGV0/y0Lp4kRVvr5NX22fSSrjdxQBF9/UwAWUObn4AF2WqroLKjPBXnzVRrAUv6Y78tGC6mWAPNlFFYu6CyAwJUvVmf1szEZdmAaG8mKrlc9AoM2z+tbkuxTJ3HNe9uDc6DIew7kNF0CoQ2/QrLa9Hpv5IUiqDoy4VVIBupq5XeRIvtszFJt1JA=
    on:
      tags: false
      branch: master
      python: 3.5
  - provider: pypi
    distributions: sdist bdist_wheel
    user: lioman
    password:
      secure: cKmaYomiF0Yxn0WRtNQXdMvRbcdG9ieir3t56VK7fJQbVxW4/4Ny8hsSWp0hvr0bA86n4CJ83ahcLgyJbzSdH4AlYA9wVvxTb3diZ+h7IfE1l3CjnRiOkmYwaqfv+e19XzwSEqGevnrYTzQ4UN/SqGM2t+H0SrBnH4SDQ6oFunZ/nUYtbH3BGoYZAY580WNpUMwM13/vjCeCcXHzD68ZCSaO/JhT+hi3XKncBQZ/dYrGqlrMjx/g0sEf4JFrRXFvZZu3uEEOqJ7MmpcX78TM1SnZjZ/FALJmJwa0wEAmbbo7THGQ4L7pDLmAz/GnVeVt90zfGk2CZ7GhVaMRjhby4+wN2Jrr05mfxYpZtCO/RyXBoBDK101g3nkXhDKzFzTpg122fQL/cXzH8zIJLEaRGA6mQsOMzc2c7JIdNSPZ5fs9uD7kUYLYwUJrS1u2UY+oslDr1lsOYQALwRaKB8BdNqB+WzmWf8Pbyy2K+PPl0F8A43UqoOiFzGV0/y0Lp4kRVvr5NX22fSSrjdxQBF9/UwAWUObn4AF2WqroLKjPBXnzVRrAUv6Y78tGC6mWAPNlFFYu6CyAwJUvVmf1szEZdmAaG8mKrlc9AoM2z+tbkuxTJ3HNe9uDc6DIew7kNF0CoQ2/QrLa9Hpv5IUiqDoy4VVIBupq5XeRIvtszFJt1JA=
    on:
      tags: true
      branch: master
      python: 3.5
script: tox